### ISSUE TITLE
searchPageText maxHits unlimited value

### ISSUE THREAD

**Issue by rybon** [andytango/mupdf-js#10]
How does one express no `maxHits` limit when invoking `searchPageText`? `0`, `-1`, `null`, `undefined`, `999`?

**Comment by andytango** [comment]
The underlying C implementation does not allow unlimited `maxHits`, otherwise the library would need dynamically allocate more memory as it finds more results. As such, setting it to zero means no hits will be returned, and setting it to any other type will throw an error.

It's not explicit why this is the case but I believe it's to keep the performance (search time) predictable, and to keep the implementation simple.

You should therefore set an appropriate level that a user would expect (for example 100), or allow users to set their own limit. 

Finally, if you really want to allow "unlimited" hits (and risk running out of memory), you can set it to C's maximum unsigned 32-bit integer size, which is `4294967295`.

Thanks for raising this, I'll update the guidance in the documentation 😄 .

**Comment by andytango** [comment]
Read me updated in https://github.com/andytango/mupdf-js/commit/27b22846440bed61a430f2e3ab6748aba05d0b8c
